    sectionWithId('ref-numpy-clip', 'Clip, pad, nan-обработка', NP_R + '#array-manipulation-routines', [
      { code: 'import numpy as np\na = np.array([-5, 2, 10, 0, 7])\nprint("clip:", np.clip(a, 0, 5))\nprint("abs:", np.abs(a))', details: 'Ограничения и модуль (абсолют).\n\n• np.clip(a, a_min, a_max) — Ограничивает (обрезает) значения в массиве.\n• Все, что меньше a_min, становится a_min; всё, что больше a_max, становится a_max.\n• В машинном обучении критически важно для предотвращения "взрыва градиентов" (gradient clipping) или избежания логарифмирования нуля np.log(clip(x, 1e-10, 1.0)).', link: NP + 'numpy.clip.html' },
      { code: 'import numpy as np\na = np.array([1, np.nan, 3, np.nan])\nprint("nan_to_num:", np.nan_to_num(a, nan=0.0))\nprint("isnan:", np.isnan(a))\nprint("nanmean:", np.nanmean(a))', details: 'Обработка пропусков (Not a Number).\n\n• np.isnan(a) — возвращает маску (где True там, где значение == NaN).\n• Обычный a.mean() вернет NaN, если в данных есть хоть один пропуск. np.nanmean(a) посчитает среднее ТОЛЬКО по реальным числам (игнорируя NaN).\n• np.nan_to_num(a, nan=0.0) — быстро заменяет все NaN, +inf, -inf на заданные числа. Удобно для очистки грязных данных перед подачей в модель.', link: NP + 'numpy.nan_to_num.html' },
      { code: 'import numpy as np\na = np.array([1, 2, 3])\nprint("pad constant:", np.pad(a, (2, 1), mode="constant", constant_values=0))\nprint("pad edge:", np.pad(a, (2, 1), mode="edge"))', details: 'Дополнение массивов (Padding).\n\n• np.pad(a, pad_width, mode) — добавляет рамку/пустые элементы вокруг массива.\n• (2, 1) означает "добавить 2 элемента слева (или сверху) и 1 элемент справа (или снизу)".\n• mode="constant" — заполняет нулями. mode="reflect" — отзеркаливает края. mode="edge" — дублирует крайние значения.\n• В CV этот метод лежит в основе "zero-padding" для сверточных сетей.', link: NP + 'numpy.pad.html' }
    ]) +
    sectionWithId('ref-numpy-io', 'Сохранение и загрузка', NP_R + '#input-and-output', [
      { code: 'import numpy as np\n# a = np.array([1.0, 2.0, 3.0])\n# np.save("data.npy", a)\n# loaded = np.load("data.npy")\nprint("save/load: .npy")', details: 'Бинарный формат Numpy.\n\n• np.save(file, a) — сохраняет один массив в супер-оптимизированный формат .npy.\n• Это в тысячи раз быстрее и компактнее текстового CSV.\n• np.load(file) — загружает сохраненный массив обратно. Сохраняет тип данных (float32 останется float32, а не float64) и размерности.\n• np.savez("archive.npz", a=a, b=b) — сохраняет СРАЗУ НЕСКОЛЬКО массивов в один сжатый .npz архив. Читается как словарь (dict).', link: NP + 'numpy.save.html' },
      { code: 'import numpy as np\n# a = np.array([[1.0, 2.0], [3.0, 4.0]])\n# np.savetxt("data.csv", a, fmt="%.2f", delimiter=",")\n# loaded = np.loadtxt("data.csv", delimiter=",")\nprint("savetxt/loadtxt: .csv / .txt")', details: 'Чтение и запись текста.\n\n• np.savetxt(file, a) — сохраняет матрицу (максимум 2D) в текстовый CSV или TXT. Отличный способ отдать данные в Excel.\n• fmt="%.2f" — форматирует числа до 2 знаков после запятой (для читаемости).\n• np.loadtxt(file) — читает из текста. Медленнее, чем pandas.read_csv, но работает "из коробки" без Pandas.\n• skip_header=1 пропустит шапку таблицы.', link: NP + 'numpy.savetxt.html' }
    ]) +
    sectionWithId('ref-numpy-advanced', 'Продвинутые функции (vectorize, meshgrid)', NP_R + '#functional-programming', [
      { code: 'import numpy as np\nx = np.array([1, 2, 3])\ny = np.array([10, 20])\nX, Y = np.meshgrid(x, y)\nprint("X:", X.tolist())\nprint("Y:", Y.tolist())', details: 'Генерация координатных сеток.\n\n• np.meshgrid(x, y) — принимает 1D-координаты и разворачивает их в две полноценные 2D-матрицы X и Y. \n• Вектор x копируется по строкам, вектор y — по столбцам (по умолчанию ij или xy-индексация).\n• Используется для вычисления функций на сетке (построение 3D-графиков $Z = X^2 + Y^2$, тепловых карт, контуров).', link: NP + 'numpy.meshgrid.html' },
      { code: 'import numpy as np\ndef my_fn(val):\n    return "Even" if val % 2 == 0 else "Odd"\nvfn = np.vectorize(my_fn)\nprint(vfn(np.array([1, 2, 3])))', details: 'Векторизация питоновских функций.\n\n• np.vectorize(func) — оборачивает любую функцию для работы с массивами (чтобы не писать цикл for).\n• Критическое уточнение: РЕАЛЬНОГО ускорения нет. Функция по-прежнему исполняется как цикл на уровне Python.\n• Назначение: удобство синтаксиса и совместимость с ndarray, а не производительность. Для скорости используйте NumPy C-функции или Numba.', link: NP + 'numpy.vectorize.html' },
      { code: 'import numpy as np\na = np.array([[1, 2], [3, 4]])\nb = np.array([[5, 6], [7, 8]])\nprint("trace (след):", np.einsum("ii", a))\nprint("умножение ij, jk -> ik:", np.einsum("ij,jk->ik", a, b))', details: 'Нотация Эйнштейна (einsum).\n\n• Универсальный швейцарский нож для тензорной алгебры.\n• "ii" — суммирование по одинаковому индексу i и i. Это след (trace) матрицы.\n• "ij,jk->ik" — матричное умножение $A \\times B = C$. i (строки A) и k (столбцы B) остаются (ik), а j (столбцы A и строки B) суммируется и исчезает.\n• Мощнейший синтаксис в Deep Learning (заменяет сложные transpose, bmm, sum) — поддерживается в PyTorch один в один.', link: NP + 'numpy.einsum.html' }
    ]);
