    sectionWithId('ref-numpy-logic', 'Логические операции', NP_R + '#logic-functions', [
      { code: 'import numpy as np\na = np.array([True, False, True, False])\nb = np.array([True, True, False, False])\nprint("AND:", np.logical_and(a, b))\nprint("OR:", np.logical_or(a, b))\nprint("XOR:", np.logical_xor(a, b))', details: 'Поэлементная булева логика.\n\n• np.logical_and(a, b) — И (обе стороны True).\n• np.logical_or(a, b) — ИЛИ (хотя бы одна True).\n• Синтаксический сахар (аналоги): a & b, a | b, ~a, a ^ b. Внимание: приоритет операторов & и | выше, чем например >, поэтому условия всегда берите в скобки: (a > 5) & (a < 10).', link: NP + 'numpy.logical_and.html' },
      { code: 'import numpy as np\na = np.array([1, 2, 3, 0, -1])\nprint("all > 0:", np.all(a > 0))\nprint("any > 0:", np.any(a > 0))\nprint("count > 0:", np.count_nonzero(a > 0))', details: 'Агрегирующая логика.\n\n• np.all(a) — возвращает True, ТОЛЬКО ЕСЛИ все элементы равны True (или не равны 0).\n• np.any(a) — возвращает True, если ХОТЯ БЫ ОДИН элемент равен True.\n• np.count_nonzero(mask) — считает количество True в маске. Гораздо быстрее, чем mask.sum().', link: NP + 'numpy.all.html' },
      { code: 'import numpy as np\na = np.array([1, 2, 3])\nb = np.array([1, 2, 4])\nprint("equal:", np.array_equal(a, b))\nprint("close:", np.allclose(a, b, atol=1))', details: 'Сравнение массивов целиком.\n\n• np.array_equal(a, b) — полная идентичность (каждый элемент и размерности должны совпадать).\n• np.allclose(a, b, atol, rtol) — проверка на "близость" чисел с плавающей точкой.\n• Из-за особенностей IEEE 754 (0.1 + 0.2 != 0.3), сравнивать float через == ЗАПРЕЩЕНО. Всегда используйте np.allclose() в тестах и метриках.', link: NP + 'numpy.allclose.html' }
    ]) +
    sectionWithId('ref-numpy-mathext', 'Математика: exp, log, тригонометрия', NP_R + '#mathematical-functions', [
      { code: 'import numpy as np\na = np.array([0, 1, 2, 3])\nprint("exp:", np.exp(a).round(4))\nprint("log:", np.log(np.array([1, np.e])))\nprint("log2:", np.log2(np.array([1, 4, 8])))', details: 'Экспоненты и логарифмы.\n\n• np.exp(x) — $e^x$, основа экспоненциальных шкал и активации Softmax.\n• np.log(x) — натуральный логарифм (по основанию $e$). Опасен при $x=0$, вернет -inf. Чтобы избежать краха модели, делают np.log(x + 1e-10) или используют np.log1p(x) для малых x.\n• np.log2 и np.log10 — логарифмы по другим основаниям (вычисление битов, децибелов).', link: NP + 'numpy.exp.html' },
      { code: 'import numpy as np\nangles = np.array([0, np.pi/6, np.pi/4, np.pi/2])\nprint("sin:", np.sin(angles).round(4))\nprint("cos:", np.cos(angles).round(4))\nprint("tan:", np.tan(np.array([0, np.pi/4])).round(4))', details: 'Тригонометрия.\n\n• Все тригонометрические функции принимают АРГУМЕНТЫ В РАДИАНАХ (НЕ в градусах).\n• Для перевода градусов в радианы: np.radians(deg) или deg * np.pi / 180.\n• Обратные функции: np.arcsin, np.arccos, np.arctan. Но для работы с полярными координатами всегда используйте np.arctan2(y, x), так как она корректно определяет квадрант (-π до π).', link: NP + 'numpy.sin.html' },
      { code: 'import numpy as np\na = np.array([1.7, -2.3, 3.5, -0.5])\nprint("floor:", np.floor(a))\nprint("ceil:", np.ceil(a))\nprint("round:", np.round(a, 0))\nprint("sign:", np.sign(a))', details: 'Округление и знаки.\n\n• np.floor(a) — жесткое округление к меньшему (вниз). $3.9 \\rightarrow 3.0$, $-2.3 \\rightarrow -3.0$.\n• np.ceil(a) — к большему (вверх). $3.1 \\rightarrow 4.0$, $-2.3 \\rightarrow -2.0$.\n• np.round(a, decimals=0) — к ближайшему четному (банковское округление! $1.5 \\rightarrow 2$, $2.5 \\rightarrow 2$).\n• np.sign(a) — возвращает -1 (для отрицательных), 0 (для 0) и 1 (для положительных).', link: NP + 'numpy.floor.html' }
    ]) +
    sectionWithId('ref-numpy-set', 'Множества', NP_R + '#set-routines', [
      { code: 'import numpy as np\na = np.array([1, 2, 3, 2, 1])\nb = np.array([3, 4, 1, 5])\nprint("unique:", np.unique(a))\nprint("intersect1d:", np.intersect1d(a, b))\nprint("setdiff1d:", np.setdiff1d(a, b))', details: 'Операции над множествами (Sets).\n\n• np.unique(a, return_counts=True) — оставляет только уникальные элементы и может вернуть их частоту (по сути гистограмма классов). Обязательно сортирует выход!\n• np.intersect1d(a, b) — пересечение (содержится и там, и там).\n• np.setdiff1d(a, b) — элементы из a, которых НЕТ в b. Полезно для вычитания списков IDs (train/val разделение).', link: NP + 'numpy.intersect1d.html' },
      { code: 'import numpy as np\na = np.array([1, 2, 3, 4, 5])\nмаска = np.isin(a, [2, 4, 6])\nprint("isin маска:", маска)\nprint("элементы:", a[маска])', details: 'Проверка принадлежности.\n\n• np.isin(element, test_elements) — Возвращает булеву маску того же размера, что и element.\n• True означает, что текущий элемент массива есть внутри списка test_elements.\n• Аналог оператора `in`, но векторизованный (применяется сразу ко всему массиву, а не к одному числу).', link: NP + 'numpy.isin.html' }
    ]) +
    sectionWithId('ref-numpy-statsext', 'Статистика: percentile, corrcoef', NP_R + '#statistics', [
      { code: 'import numpy as np\na = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])\nprint("25%:", np.percentile(a, 25))\nprint("Медиана (50%):", np.percentile(a, 50))\nprint("75%:", np.percentile(a, 75))', details: 'Процентили и квантили.\n\n• np.percentile(a, q) — q (в диапазоне от 0 до 100) — значение, ниже которого лежит q% всех данных массива.\n• np.quantile(a, q) — то же самое, но q в диапазоне от 0 до 1.\n• np.median(a) — ровно 50-й процентиль.\n• Используются для интерквартильного размаха (IQR = P75 - P25), это стандартный способ фильтрации жестких выбросов (outliers) в ML.', link: NP + 'numpy.percentile.html' },
      { code: 'import numpy as np\nnp.random.seed(42)\nx = np.random.rand(50)\ny = x * 2 + np.random.randn(50) * 0.1\ncov = np.cov(x, y)\ncorr = np.corrcoef(x, y)\nprint("Covariance:\\n", cov.round(2))\nprint("Correlation:\\n", corr.round(2))', details: 'Ковариация и Корреляция.\n\n• np.cov(x, y) — ковариационная матрица. На главной диагонали — дисперсии (variance).\n• np.corrcoef(x, y) — Пирсоновская матрица корреляций (значения от -1 до +1). +1 означает идеальную прямую зависимость, 0 — независимы.\n• Высокая корреляция между признаками (фичами) ломает линейные модели из-за мультиколлинеарности. Матрица корреляций помогает их выявлять.', link: NP + 'numpy.corrcoef.html' }
    ]) +
    sectionWithId('ref-numpy-string', 'Форматирование и вывод', NP_R + '#string-operations', [
      { code: 'import numpy as np\nnp.set_printoptions(precision=3, suppress=True, linewidth=100)\na = np.array([1/3, np.pi, 1e-10])\nprint("Формат:", a)\nnp.set_printoptions()  # Сброс к дефолту', details: 'Управление отображением.\n\n• np.set_printoptions() глобально меняет то, как numpy печатает матрицы в консоли.\n• precision=3 (сколько знаков после запятой).\n• suppress=True (отключить научную нотацию 1.00e-10 и выводить 0.000).\n• threshold=10 (если элементов больше 10, массив обрежется через троеточие [...]). Влияет ТОЛЬКО на вывод (print), не трогает реальные байты данных.', link: NP + 'numpy.set_printoptions.html' }
    ]);
