    sectionWithId('ref-numpy-index', 'Индексация и срезы (slices)', NP_R + '#indexing-routines', [
      { code: 'import numpy as np\na = np.arange(10)\nprint("Срез [2:5]:", a[2:5])\nprint("С шагом [::2]:", a[::2])\nprint("Разворот [::-1]:", a[::-1])', details: 'Базовая индексация (slice).\n\n• Синтаксис: a[start:stop:step]. Индексы начинаются с нуля. Отрицательные — с конца.\n• Возвращает VIEW, а не копию! a[2:5] = 10 изменит оригинальный массив (в отличие от Python list, где это делает копию).\n• Запись arr[:] копирует только представление элементов, arr.copy() создает полную C-совместимую копию данных.', link: NP + 'numpy.ndarray.copy.html' },
      { code: 'import numpy as np\na = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])\nprint("Элемент 1,2:", a[1, 2])\nprint("Строка 1:", a[1, :])\nprint("Столбец 2:", a[:, 2])', details: 'Многомерные срезы.\n\n• В NumPy передаётся кортеж: a[строка, столбец] (в Python list пришлось бы писать a[1][2]).\n• a[:, 2] (двоеточие) означает "взять все элементы по этой оси". Отлично подходит для разделения признаков (X) и целевой переменной (y): X = data[:, :-1], p_y = data[:, -1].\n• Можно передать многоточие (Ellipsis): a[..., 0] — первый канал из N-мерного изображения.', link: NP_R + '#indexing' },
      { code: 'import numpy as np\na = np.array([1, 2, 3, 4, 5])\nмаска = a % 2 == 0\nprint("Маска:", маска)\nprint("Элементы по маске:", a[маска])\na[a < 3] = 0\nprint("Замена:", a)', details: 'Булева индексация (маскирование).\n\n• Операция типа a > 2 возвращает массив булевых True/False (маску).\n• a[маска] возвращает массив только тех элементов a, где маска равна True.\n• Широко используется для чистки датасета: df[df.age > 18] или X[np.isnan(X)] = 0. Массовые замены через a[x<0]=0 быстрее, чем цикл.', link: NP_R + '#boolean-array-indexing' }
    ]) +
    sectionWithId('ref-numpy-sort', 'Сортировка и поиск', NP_R + '#sorting-searching-and-counting', [
      { code: 'import numpy as np\na = np.array([3, 1, 2])\nprint("sorted:", np.sort(a))\nprint("argsort:", np.argsort(a))\nprint("возврат по arg:", a[np.argsort(a)])', details: 'Сортировка массивов.\n\n• np.sort(a) — возвращает отсортированную КОПИЮ массива.\n• a.sort() — сортирует массив НА МЕСТЕ (inplace).\n• np.argsort(a) — возвращает ИНДЕКСЫ, по которым массив был бы отсортирован. Безумно полезно, если нужно отсортировать массив X на основе значений массива y (X[np.argsort(y)]).', link: NP + 'numpy.sort.html' },
      { code: 'import numpy as np\na = np.array([1, 0, 5, 0, 3])\nprint("nonzero:", np.nonzero(a))\nprint("where >0:", np.where(a > 0)[0])\nprint("where + замена:", np.where(a > 0, a, -1))', details: 'Поиск позиций (индексов).\n\n• np.nonzero(a) — индексы ненулевых элементов (или где маска True).\n• np.where(cond, x, y) — векторный if/else. Возвращает x там, где cond == True, и y там, где False. Идеально для бинаризации предсказаний: predictions = np.where(proba > 0.5, 1, 0).\n• np.argwhere(a) — возвращает индексы в виде матрицы N x ndim.', link: NP + 'numpy.where.html' }
    ]) +
    sectionWithId('ref-numpy-reshape', 'Reshape и перестройка массивов', NP_R + '#array-manipulation-routines', [
      { code: 'import numpy as np\na = np.array([[1, 2], [3, 4]])\nprint("ravel:", a.ravel())\nprint("flatten:", a.flatten())\nprint("is_view:", np.shares_memory(a, a.ravel()))', details: 'Разворачивание (flattening) в 1D.\n\n• a.ravel() — всегда старается вернуть view (ссылку на старую память). Очень быстрый, но изменение ravel() затронет a.\n• a.flatten() — всегда создает НОВУЮ КОПИЮ в памяти. Более безопасно, но дольше. Все картинки перед подачей в Linear слои разворачиваются (через view в PyTorch или reshape).', link: NP + 'numpy.ravel.html' },
      { code: 'import numpy as np\na = np.array([1, 2, 3])\nprint("expand_dims 0:", np.expand_dims(a, axis=0).shape)\nprint("expand_dims 1:", np.expand_dims(a, axis=1).shape)\nprint("newaxis:", a[np.newaxis, :].shape)', details: 'Увеличение / уменьшение размерности.\n\n• np.expand_dims(a, axis) — вставляет новую ось длины 1. axis=0 превращает (3,) в (1,3). axis=1 превращает (3,) в (3,1).\n• Идентичный синтаксис: a[np.newaxis, :]  или a[:, None]. Это нужно для broadcasting, либо имитации батча (1, H, W, C) для 1 картинки перед инференсом сети.\n• np.squeeze(a) — обратная операция: удаляет все оси длины 1 (из (1, 3, 1) сделает (3,)).', link: NP + 'numpy.expand_dims.html' },
      { code: 'import numpy as np\na = np.array([[1, 2, 3], [4, 5, 6]])\nprint("T (Транспонирование):", a.T.shape)\nprint("swapaxes:", np.swapaxes(a, 0, 1).shape)', details: 'Смена порядка осей (Transposing).\n\n• a.T — разворот матрицы. Строки становятся столбцами, столбцы — строками.\n• np.swapaxes(a, axis1, axis2) — меняет местами две любые оси.\n• Для тензоров >2D: np.transpose(a, axes=(0, 2, 1)) — ручная расстановка осей (например (B, H, W, C) -> (B, C, H, W) для PyTorch).', link: NP + 'numpy.transpose.html' }
    ]) +
    sectionWithId('ref-numpy-combine', 'Объединение и разделение', NP_R + '#array-manipulation-routines', [
      { code: 'import numpy as np\na = np.array([[1, 2], [3, 4]])\nb = np.array([[5, 6], [7, 8]])\nprint("vstack (по вертикали):\\n", np.vstack((a, b)))\nprint("hstack (по горизонтали):\\n", np.hstack((a, b)))', details: 'Вспомогательные (удобные) склейки.\n\n• np.vstack (Vertical Stack) — склеивает массивы по строкам (добавляет новые строки). Аналог объединения dataset-ов (в ML).\n• np.hstack (Horizontal Stack) — склеивает по столбцам (добавляет фичи / признаки).\n• Формы склеиваемых массивов должны совпадать по всем размерностям, кроме той, по которой идет склейка.', link: NP + 'numpy.vstack.html' },
      { code: 'import numpy as np\na = np.array([1, 2])\nb = np.array([3, 4])\nprint("concatenate:", np.concatenate((a, b), axis=0))\nprint("stack (новая ось):", np.stack((a, b), axis=0).shape)', details: 'Генеральная склейка.\n\n• np.concatenate(tuple, axis) — склеивает вдоль СУЩЕСТВУЮЩЕЙ оси (например, собирает 10 батчей по 32 картинки в (320, H, W, C)).\n• np.stack(tuple, axis) — объединяет через создание НОВОЙ оси (собирает 32 картинки (H, W, C) в батч (32, H, W, C)).', link: NP + 'numpy.concatenate.html' },
      { code: 'import numpy as np\na = np.arange(9)\nprint("split (3 части):", np.split(a, 3))\nprint("split (по индексам):", np.split(a, [2, 5]))\nprint("hsplit:", np.hsplit(a.reshape(3,3), 3))', details: 'Разделение массивов.\n\n• np.split(a, N) — режет на N равных частей. Выкинет ошибку, если a.size % N != 0.\n• np.array_split(a, N) — как split, но разрешает неравные части (полезно при разбивке данных на батчи).\n• При передаче массива индексов [2, 5], массив режется в этих конкретных позициях.', link: NP + 'numpy.split.html' }
    ]);
