    sectionWithId('ref-pandas-sort', 'Сортировка и ранжирование', PD + 'pandas.DataFrame.sort_values.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [3, 1, 2], "B": ["c", "a", "b"]})\nprint("sort_values:\\n", df.sort_values(by="A", ascending=False))\nprint("sort_index:\\n", df.sort_index(ascending=True))', details: 'Упорядочивание строк (Сортировка).\n\n• df.sort_values(by="A") — Опирается на ЗНАЧЕНИЯ столбца "A".\n• by может быть списком ["A", "B"] (сначала по A, если равны, то по B).\n• ascending=False — включает сортировку по Убыванию.\n• df.sort_index() — сортирует сами метки-индексы. Полезно для восстановления порядка TimeSeries после перетасовки данных.', link: PD + 'pandas.DataFrame.sort_values.html' },
      { code: 'import pandas as pd\ns = pd.Series([10, 10, 20, 30])\nprint("rank (average):\\n", s.rank().tolist())\nprint("rank (min):\\n", s.rank(method="min").tolist())', details: 'Ранжирование (Ranks).\n\n• s.rank() — Выставляет позицию (ранг) каждого элемента.\n• Если значения равны (Tied scores), метод рассчитывает средний ранг (average), минимальный (min), максимальный (max) или первый попавшийся (first).\n• В ML (Spearman Correlation, non-parametric tests) данные часто заменяют на их ранги для устойчивости к выбросам.', link: PD + 'pandas.Series.rank.html' }
    ]) +
    sectionWithId('ref-pandas-window', 'Окна: rolling, expanding, ewm', PD + 'pandas.DataFrame.rolling.html', [
      { code: 'import pandas as pd\nimport numpy as np\ns = pd.Series([1, 2, 3, 4, 5])\nprint("rolling(3).mean():\\n", s.rolling(window=3).mean().tolist())\nprint("expanding().sum():\\n", s.expanding().sum().tolist())', details: 'Скользящие окна (Moving averages - SMA).\n\n• s.rolling(window=k) — Создает окошко шириной k, которое скользит по ряду.\n• k=3 означает: "взять текущее плюс два предыдущих, найти .mean()". Это сглаживает графики и волатильность в трейдинге.\n• s.expanding() — Окно, которое растет. k берет ВСЕ данные от начала массива до текущей строки. Используется для кумулятивных метрик (например Cumulative Sum).', link: PD + 'pandas.DataFrame.rolling.html' },
      { code: 'import pandas as pd\ns = pd.Series([10, 20, 30, 40, 50])\nema = s.ewm(span=3, adjust=False).mean()\nprint("Экспоненциальное скользящее среднее (EMA):\\n", ema.round(2).tolist())', details: 'Экспоненциальные окна (EMA).\n\n• s.ewm(span=k) — Экспоненциальное скользящее среднее.\n• В отличие от обычного окна (роллинг), где все числа "весят" одинаково, здесь новые данные "важнее", чем старые.\n• Эта метрика меньше запаздывает (lag) за реальным графиком и является основой большинства индикаторов технического анализа (MACD) и градиентного спуска с моментом (Momentum/Adam).', link: PD + 'pandas.DataFrame.ewm.html' }
    ]) +
    sectionWithId('ref-pandas-merge', 'Объединение: merge, concat, join', PD + 'pandas.DataFrame.merge.html', [
      { code: 'import pandas as pd\ndf1 = pd.DataFrame({"key": ["K0", "K1"], "A": [1, 2]})\ndf2 = pd.DataFrame({"key": ["K0", "K1"], "B": [3, 4]})\nprint("merge inner:\\n", pd.merge(df1, df2, on="key", how="inner"))\nprint("merge left:\\n", pd.merge(df1, df2, on="key", how="left"))', details: 'Слияние по ключу (SQL JOIN).\n\n• pd.merge() — Классическое соединение двух таблиц по общим столбцам.\n• how="inner" — оставляет только общие ключи (как A ∩ B).\n• how="left" — оставляет все ключи из левой таблицы, а из правой "тянет" что нашлось (иначе NaN).\n• how="outer" — оставляет ВСЁ (A ∪ B). Супер-важный метод сборки единого датафрейма из разрозненных таблиц базы данных.', link: PD + 'pandas.DataFrame.merge.html' },
      { code: 'import pandas as pd\ndf1 = pd.DataFrame({"A": [1, 2]}, index=[1,2])\ndf2 = pd.DataFrame({"A": [3, 4]}, index=[3,4])\nprint("concat rows:\\n", pd.concat([df1, df2], axis=0))\nprint("concat cols:\\n", pd.concat([df1, df2], axis=1))', details: 'Конкатенация (склейка скотчем).\n\n• pd.concat([d1, d2]) — Просто прилепляет один датафрейм под другим (axis=0) или рядом друг с другом (axis=1).\n• Не ищет никаких общих "ключей" для слияния, кроме индексов. Если вы склеиваете по оси O (вниз), колонки с одинаковыми именами встанут друг под друга.\n• df.append() — устарел и удален в новых версиях, используйте только pd.concat().', link: PD + 'pandas.concat.html' },
      { code: 'import pandas as pd\ndf1 = pd.DataFrame({"A": [1, 2]}, index=["K1", "K2"])\ndf2 = pd.DataFrame({"B": [3, 4]}, index=["K1", "K3"])\nprint("join:\\n", df1.join(df2, how="outer"))', details: 'Слияние по ИНДЕКСУ.\n\n• df1.join(df2) — это вариант merge, но строго заточенный под использование индексов строки как ключей слияния.\n• Гораздо лаконичнее, чем merge() с left_index=True и right_index=True.', link: PD + 'pandas.DataFrame.join.html' }
    ]) +
    sectionWithId('ref-pandas-manage', 'Управление: drop, rename, set_index', PD + 'pandas.DataFrame.drop.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [1, 2], "B": [3, 4]})\nprint("drop col:\\n", df.drop(columns=["A"]))\nprint("drop row:\\n", df.drop(index=[0]))', details: 'Удаление строк и столбцов.\n\n• df.drop(columns=["A"]) — Удаляет весь столбец (он же df.drop("A", axis=1)).\n• df.drop(index=[0]) — Удаляет всю нулевую строку (он же df.drop(0, axis=0)).\n• inplace=True — Меняет исходную таблицу прямо в памяти, не создавая копию-дубликат (экономит ОЗУ при обработке сетов по 50 Гб).', link: PD + 'pandas.DataFrame.drop.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [1, 2], "ID": ["x", "y"]})\ndf.rename(columns={"A": "Alpha"}, inplace=True)\ndf.set_index("ID", inplace=True)\nprint(df)\ndf.reset_index(inplace=True)\nprint(df)', details: 'Переименования и перенос индексов.\n\n• df.rename(columns={"old": "new"}) — Переименовывает колонки по словарю. Очень полезно для избавления от пробелов в именах колонок.\n• df.set_index("col") — Берет обычную колонку и делает ее "ключом" (Index) датафрейма (например ID клиента или Date).\n• df.reset_index() — Извлекает "ключ" (Index) обратно в обычную колонку и присваивает датафрейму стандартные номера 0, 1, 2, ...', link: PD + 'pandas.DataFrame.rename.html' }
    ]);
