  // ---- Pandas: содержание и разделы по темам ----
  var pandasToc = [
    { id: 'ref-pandas-import', title: 'Импорт и структуры данных' },
    { id: 'ref-pandas-read', title: 'Чтение и запись данных' },
    { id: 'ref-pandas-view', title: 'Инспекция (head, info, describe)' },
    { id: 'ref-pandas-select', title: 'Выборка (loc, iloc, маски)' },
    { id: 'ref-pandas-missing', title: 'Пропуски данных (NaN)' },
    { id: 'ref-pandas-group', title: 'Группировка (groupby, agg)' },
    { id: 'ref-pandas-ml', title: 'Для машинного обучения' },
    { id: 'ref-pandas-str', title: 'Строковые методы (.str)' },
    { id: 'ref-pandas-reshape', title: 'Reshape: pivot, melt, stack' },
    { id: 'ref-pandas-apply', title: 'apply, map, transform, pipe' },
    { id: 'ref-pandas-sort', title: 'Сортировка и ранжирование' },
    { id: 'ref-pandas-window', title: 'Окна: rolling, expanding, ewm' },
    { id: 'ref-pandas-merge', title: 'Объединение: merge, concat, join' },
    { id: 'ref-pandas-manage', title: 'Управление: drop, rename, set_index' },
    { id: 'ref-pandas-dummies', title: 'Кодирование и дубликаты' },
    { id: 'ref-pandas-stats', title: 'Статистика и корреляции' },
    { id: 'ref-pandas-datetime', title: 'Даты и время' }
  ];

  var pandasTheory =
    sectionWithId('ref-pandas-import', 'Импорт и структуры данных', PD + 'pandas.DataFrame.html', [
      { code: 'import pandas as pd\nprint(pd.__version__)', details: 'Общепринятый алиас.\n\n• Импорт как `pd` — стандарт де-факто в Data Science.\n• Pandas построен поверх NumPy, поэтому все вычисления под капотом векторизованы и очень быстры.\n• Основное предназначение: табличные данные (SQL таблицы, Excel, CSV), временные ряды и очистка датасетов перед подачей их в ML-модели.', link: PD + 'pandas.DataFrame.html' },
      { code: 'import pandas as pd\ns = pd.Series([10, 20, 30], index=["a", "b", "c"])\nprint("Series:\\n", s)', details: 'Объект Series (серия).\n\n• Pandas Series — это одномерный массив с ИНДЕКСОМ (в отличие от numpy-массивов). Это похоже на упорядоченный словарь.\n• Индексы могут быть числами, строками (именами) или датами. Именно по этому индексу столбцы "выравниваются" (align) при сложении.\n• Каждый столбец в таблице (DataFrame) — это один объект типа Series.', link: PD + 'pandas.Series.html' },
      { code: 'import pandas as pd\ndata = {"Имя": ["Анна", "Борис"], "Возраст": [25, 30]}\ndf = pd.DataFrame(data)\nprint("DataFrame:\\n", df)', details: 'Объект DataFrame (датафрейм).\n\n• DataFrame — это 2D таблица, состоящая из колонок (столбцов). Каждая колонка — это Series.\n• Отлично создается из словарей (dict), списков списков, numpy-массивов или читается из файлов.\n• Поддерживает гетерогенные данные: в одной таблице одновременно могут быть целые числа (int), строки (object/string) и даты (datetime).', link: PD + 'pandas.DataFrame.html' }
    ]) +
    sectionWithId('ref-pandas-read', 'Чтение и запись данных', PD + 'pandas.read_csv.html', [
      { code: 'import pandas as pd\n# df = pd.read_csv("data.csv", index_col=0)\n# df.to_csv("out.csv", index=False)\nprint("read_csv() / to_csv()")', details: 'Работа с файлами CSV.\n\n• pd.read_csv() — самая частая команда для импорта данных.\n• Ключевые параметры: sep (разделитель, часто ; или ,), index_col (какой столбец использовать как индекс), parse_dates (какие столбцы парсить как даты).\n• pd.to_csv() — сохранение результата на диск. Обязательно ставьте index=False, если ваш индекс — простые числа 0, 1, 2, иначе pandas запишет этот индекс как лишний столбец "Unnamed: 0".', link: PD + 'pandas.read_csv.html' },
      { code: 'import pandas as pd\n# df = pd.read_excel("data.xlsx", sheet_name="Sheet1")\n# df.to_excel("out.xlsx", index=False)\nprint("read_excel() / to_excel()")', details: 'Работа с файлами Excel.\n\n• pd.read_excel() — чтение .xlsx или .xls.\n• Позволяет загружать данные с конкретной страницы (sheet_name).\n• Для работы требуются библиотеки openpyxl (для xlsx) или xlrd (для старых xls).\n• Аналогично работает сохранение — to_excel() поддерживает запись в множество листов через объект ExcelWriter.', link: PD + 'pandas.read_excel.html' },
      { code: 'import pandas as pd\n# df = pd.read_parquet("data.parquet")\n# df.to_parquet("out.parquet")\nprint("read_parquet() / to_parquet()")', details: 'Работа с Parquet (Big Data формат).\n\n• Parquet — мощнейший столбцово-ориентированный формат. Он во много раз компактнее и читается в 10-100 раз быстрее, чем CSV.\n• Жестко сохраняет типы колонок (datetime остается datetime, int32 остается int32). CSV этой информации не хранит.\n• Требует установки библиотеки pyarrow или fastparquet. Обязательный стандарт для больших датасетов в ML-соревнованиях.', link: PD + 'pandas.read_parquet.html' }
    ]) +
    sectionWithId('ref-pandas-view', 'Инспекция, просмотр и сводка', PD + 'pandas.DataFrame.head.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"age": [20, 30, 40], "sal": [10, 20, 30]})\nprint(df.head(2))\nprint(df.tail(1))', details: 'Просмотр начала и конца таблицы.\n\n• df.head(n=5) — возвращает первые 5 строк. Используйте всегда сразу после загрузки файла, чтобы убедиться, что парсинг прошел успешно и колонки на месте.\n• df.tail(n=5) — возвращает последние n строк. Полезно для проверки правильности загрузки временных рядов (догрузились ли самые свежие даты).\n• df.sample(n) — берет случайные n строчек.', link: PD + 'pandas.DataFrame.head.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [1, 2], "B": ["x", "y"]})\nprint("shape:", df.shape)\nprint("columns:", df.columns.tolist())\ndf.info()', details: 'Общая информация о датафрейме.\n\n• df.shape — кортеж (строки, столбцы). Базовая проверка размера данных.\n• df.columns — список имен столбцов. Можно переприсвоить для массового переименования: df.columns = ["new1", "new2"].\n• df.info() — супер-команда. Выводит типы данных каждой колонки, использование RAM (важно в Big Data) и, самое главное, количество не-null значений (быстрый поиск столбцов с дырами).', link: PD + 'pandas.DataFrame.info.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"sale": [100, 200, 300, 1000]})\nprint(df.describe(percentiles=[0.05, 0.95]))', details: 'Быстрая описательная статистика.\n\n• df.describe() — мгновенно выводит для всех числовых колонок: count, mean, std, min, max и процентили (по умолчанию 25%, 50%, 75%).\n• Если min и max сильно отличаются от квартилей (25-75%), значит в данных есть мощные выбросы (outliers), которые могут сломать ML-модель.\n• Можно применять и к строковым колонкам: describe(include="O") — покажет количество уникальных значений (unique) и самое популярное (top).', link: PD + 'pandas.DataFrame.describe.html' }
    ]) +
    sectionWithId('ref-pandas-select', 'Выборка данных: loc, iloc и маски', PD + 'pandas.DataFrame.loc.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [10, 20], "B": [30, 40]}, index=["row1", "row2"])\nprint("По имени (loc):", df.loc["row1", "A"])\nprint("По индексу (iloc):", df.iloc[0, 1])', details: 'Выбор подмножества данных (индексация).\n\n• В pandas два главных индексатора: loc и iloc.\n• .loc[строки, колонки] — используется для доступа ПО ИМЕНИ (по меткам). Например, df.loc["2024-01-01":"2024-12-31", "Sales"].\n• .iloc[строки, колонки] — используется для доступа ПО ПОЗИЦИИ (по индексу массива NumPy, всегда целые числа). df.iloc[0:10, 1] — первые десять строк из второго столбца.', link: PD + 'pandas.DataFrame.loc.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"user": ["U1", "U2", "U3"], "age": [17, 25, 30]})\nmask = df["age"] > 18\nprint(df[mask])', details: 'Булева индексация (фильтрация).\n\n• Аналог WHERE в SQL.\n• Берем столбец, пишем условие (возвращает Series булевых True/False), и передаем в df[условие].\n• Можно объединять маски скобками и битовыми операторами! df[(df["age"] > 18) & (df["age"] < 65)].\n• Можно использовать df.query("age > 18 and age < 65") — этот строковый синтаксис иногда быстрее для больших вычислений.', link: PD + 'pandas.DataFrame.loc.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"city": ["NY", "LA", "NY", "SF"]})\nprint("unique:", df["city"].unique())\nprint("value_counts:\\n", df["city"].value_counts())', details: 'Уникальные значения и подсчет (частотный анализ).\n\n• col.unique() — возвращает numpy-список уникальных значений в столбце.\n• col.nunique() — количество уникальных элементов (Number of Unique). Часто используется для определения, является ли признак категориальным (если уникальных < 100) или непрерывным.\n• col.value_counts() — самая частая команда для EDA. Строит распределение, считает частоты категорий. Если передать normalize=True, выдаст доли (проценты) вместо абсолютных чисел.', link: PD + 'pandas.Series.value_counts.html' }
    ]) +
    sectionWithId('ref-pandas-missing', 'Менеджмент пропусков (NaN, None)', PD + 'pandas.DataFrame.dropna.html', [
      { code: 'import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({"A": [1, np.nan, 3], "B": [np.nan, 5, 6]})\nprint("isnull sum:\\n", df.isnull().sum())', details: 'Поиск и диагностика пропусков.\n\n• В pandas пустые ячейки (Missing Data) всегда обозначаются как NaN (Not a Number) из NumPy.\n• df.isnull() или df.isna() — возвращает матрицу True (где пропуск) и False.\n• df.isnull().sum() — стандартная конструкция для подсчета количества дыр в КАЖДОЙ колонке (суммируются True по столбцам). Если дыр > 50%, фичу часто "выбрасывают" из ML-пайплайна.', link: PD + 'pandas.DataFrame.isnull.html' },
      { code: 'import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({"A": [1, np.nan, 3]})\nprint("dropna:", df.dropna())\nprint("fillna:", df.fillna(0))\nprint("fillna mean:", df.fillna(df["A"].mean()))', details: 'Удаление или заполнение пропусков (Imputation).\n\n• df.dropna() — агрессивно удаляет ЦЕЛИКОМ СТРОКИ, в которых есть хотя бы один NaN. Если данных мало, вы удалите половину датасета.\n• dropna(axis=1) — удаляет колонки с NaN.\n• df.fillna(value) — заменяет каждый NaN на value. В ML часто делают заполнение средним/медианой (df.fillna(df.median())) или модой (самым частым значением). Для временных рядов используют методы ffill (перенос вперед) и bfill.', link: PD + 'pandas.DataFrame.fillna.html' }
    ]);
