    sectionWithId('ref-pandas-dummies', 'Кодирование и дубликаты', PD + 'pandas.DataFrame.duplicated.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"age": [10, 10, 10, 20], "name": ["A", "A", "B", "C"]})\nprint("Записи-дубликаты целиком:\\n", df.duplicated())\nprint("Дубликаты по имени:\\n", df.duplicated(subset=["name"]))', details: 'Поиск дубликатов.\n\n• df.duplicated() — Находит строки, которые полностью идентичны с предыдущими.\n• Возвращает булеву маску (True/False).\n• subset=["col"] — находит записи, у которых одинаковое значение в конкретной колонке (полезно для поиска одинаковых емейлов или ID).\n• keep="first" (оставляет первый оригинал False), "last" (оставляет последний), False (помечает ВСЕ копии как True).', link: PD + 'pandas.DataFrame.duplicated.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"age": [10, 10, 10, 20], "name": ["A", "A", "B", "C"]})\nprint("Без дубликатов:\\n", df.drop_duplicates())\nprint("Без дубликатов имен:\\n", df.drop_duplicates(subset=["name"], keep="last"))', details: 'Удаление дубликатов.\n\n• df.drop_duplicates() — Чистит датафрейм от полных копий (очень важно для дедупликации собранных с парсера данных).\n• keep="last" гарантирует, что из 10 дублей выживет именно последняя записанная версия (например, последнее редактирование профиля).', link: PD + 'pandas.DataFrame.drop_duplicates.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"val": [-100, 2, 5, 100]})\nprint("clip:", df.clip(lower=0, upper=10))\nprint("replace:", df.replace({-100: 0, 100: 10}))', details: 'Отсечение и Замена значений.\n\n• df.clip(lower, upper) — Обрезает значения, выходящие за границы (чтобы убить выбросы без удаления самих строк датасета).\n• df.replace(to_replace, value) — Аналог Ctrl+F в Excel. Заменяет конкретные числа/строки на другие. Например df.replace("Unknown", np.nan) — супер прием для подготовки грязных таблиц к .dropna().', link: PD + 'pandas.DataFrame.clip.html' }
    ]) +
    sectionWithId('ref-pandas-stats', 'Статистика и корреляции', PD + 'pandas.DataFrame.corr.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 2]})\nprint("cov:\\n", df.cov())\nprint("corr:\\n", df.corr())\nprint("corr spearman:\\n", df.corr(method="spearman"))', details: 'Корреляция признаков.\n\n• df.corr() — Главный метод для построения Матрицы Корреляций Пирсона. Она показывает линейную взаимосвязь (-1 до 1) каждой фичи с каждой.\n• Важнейший инструмент Анализа Данных (EDA): если фича скоррелирована с таргетом (y) на 0.8 — это топ-фича (отличный предиктор). Если две входных фичи скоррелированы между собой на 0.99 — одну из них ОБЯЗАТЕЛЬНО нужно удалить (это мультиколлинеарность).\n• method="spearman" или "kendall" — корреляция для нелинейных или ранжированных данных (устойчива к выбросам).', link: PD + 'pandas.DataFrame.corr.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": [1, 2, 3, 2, 1, np.nan]})\nprint("mean:", df["A"].mean())\nprint("median:", df["A"].median())\nprint("mode:", df["A"].mode().values)\nprint("std:", df["A"].std())', details: 'Базовые метрики (игнорируют NaN).\n\n• В отличие от чистого numpy (np.mean()), функции Pandas по умолчанию ПРОПУСКАЮТ значения NaN, не превращая результат в "дыру".\n• df.mean() — Среднее арифметическое (опасно: подвержено выбросам).\n• df.median() — Медиана (робастна, то есть игнорирует случайные аномальные спайки).\n• df.mode() — Мода, самое частое значение (шикарно подходит для импутации строковых пропусков: df.fillna(df.mode()[0])).', link: PD + 'pandas.DataFrame.mean.html' }
    ]) +
    sectionWithId('ref-pandas-datetime', 'Даты и время', PD + 'pandas.to_datetime.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"Date": ["2020-01-01", "2020-02-01"]})\ndf["DT"] = pd.to_datetime(df["Date"])\nprint("to_datetime:", df.dtypes)\nprint("Взять месяц:", df["DT"].dt.month.tolist())', details: 'Парсинг Времени и Выделение фичей (.dt).\n\n• Когда вы читаете CSV, даты там всегда в виде текста (object/string). pd.to_datetime(s) — переводит их в формат Timestamp.\n• формат: pd.to_datetime(s, format="%d.%m.%Y") — для нестандартных парсеров (день.месяц.год).\n• df["DT"].dt. — Специальный аксессор для дат (как .str для строк). Через него можно мгновенно дергать: .dt.year, .dt.month, .dt.dayOfWeek, .dt.is_leap_year. Из одной колонки с датой можно сделать 10 новых фичей для нейросети!', link: PD + 'pandas.to_datetime.html' },
      { code: 'import pandas as pd\ndr = pd.date_range(start="2020-01-01", periods=3, freq="D")\ndf = pd.DataFrame({"val": [10, 20, 30]}, index=dr)\nprint("date_range:\\n", df)\nres = df.resample("ME").mean()\nprint("resample(Month End):\\n", res)', details: 'Ряды и Resampling (Даунсемплинг).\n\n• pd.date_range() — Генерирует массив дат. freq="D" (дни), freq="15min" (15 минут), freq="MS" (Month Start).\n• df.resample("ME") — Если дата стоит в индексе (КРИТИЧЕСКИ ВАЖНО!), этот метод позволяет "сжать" данные. Был график по дням — стал по месяцам ("ME" = Month End). К нему нужно прикрутить агрегацию (.mean() или .sum()), чтобы объяснить Pandas, как схлопнуть значения.\n• Ресэмплинг — база прогнозирования временных рядов (Time-Series Forecasting).', link: PD + 'pandas.DataFrame.resample.html' }
    ]);
