    sectionWithId('ref-pandas-group', 'Группировка (groupby, agg)', PD + 'pandas.DataFrame.groupby.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"class": ["A", "B", "A", "B"], "score": [90, 80, 70, 60]})\ngrouped = df.groupby("class").mean()\nprint(grouped)', details: 'Сплит, Применение, Объединение.\n\n• df.groupby("col") — собирает все строки с одинаковыми значениями в колонке "col" (как GROUP BY в SQL).\n• .mean(), .sum(), .count(), .max(), .min() — агрегирует метрики для каждой группы.\n• groupby возвращает DataFrame, где колонки группировки стали ИНДЕКСОМ новой таблицы! Чтобы вернуть их в обычные колонки, добавьте .reset_index() после расчета средних.', link: PD + 'pandas.DataFrame.groupby.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"class": ["A", "B", "A"], "score": [90, 80, 70], "age": [20, 22, 21]})\nagg_df = df.groupby("class").agg(\n    {"score": ["mean", "max"], "age": "min"}\n)\nprint(agg_df)', details: 'Сложные агрегации (.agg).\n\n• Позволяет применять РАЗНЫЕ функции к РАЗНЫМ числовым столбцам.\n• Можно передать словарь функций: {"столбец": ["список", "статистик"]}.\n• Это создает иерархический мультииндекс (MultiIndex) на колонках (вы увидите сдвоенную "шапку" DataFram\'a). Чтобы сделать ее плоской: agg_df.columns = ["_".join(cols) for cols in agg_df.columns].', link: PD + 'pandas.DataFrame.agg.html' }
    ]) +
    sectionWithId('ref-pandas-ml', 'Утилиты для Data Science и ML', PD + 'pandas.get_dummies.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"id": [1, 2], "color": ["Red", "Blue"]})\nprint("One-Hot Encoding:")\nprint(pd.get_dummies(df, columns=["color"], drop_first=True))', details: 'Кодирование категорий прямо в Pandas.\n\n• pd.get_dummies() мгновенно превращает текстовые ("Red", "Blue") в бинарные колонки (color_Red=1, color_Blue=0).\n• Это One-Hot Encoding в чистом виде (чтобы модель не считала 2 > 1).\n• drop_first=True ОБЯЗАТЕЛЬНО для линейных моделей: удаляет первый бинарник, чтобы избежать мультиколлинеарности матриц (фичи становятся линейно независимыми).', link: PD + 'pandas.get_dummies.html' },
      { code: 'import pandas as pd\ndata = pd.Series([10, 20, 30, 40, 50, 60])\nprint("Bins:", pd.cut(data, bins=3))\nprint("Quantiles:", pd.qcut(data, q=3))', details: 'Биннинг (Дискретизация) признака.\n\n• pd.cut(bins=3) — разбивает числовой признак на 3 РАВНЫХ ПО РАЗМЕРУ интервала.\n• pd.qcut(q=3) — разбивает на квантили. То есть 3 группы, В КОТОРЫХ ОДИНАКОВОЕ ЧИСЛО СТРОК (например треть бедных, треть среднего класса, треть богатых).\n• Деревья решений часто справляются с цифрами сами, но для линейных моделей и анализа биннинг сильно помогает находить нелинейности.', link: PD + 'pandas.qcut.html' }
    ]) +
    sectionWithId('ref-pandas-str', 'Строковые методы (.str)', PD + 'pandas.Series.str.html', [
      { code: 'import pandas as pd\ns = pd.Series(["Hello World", "foo bar", "PYTHON"])\nprint("lower:", s.str.lower().tolist())\nprint("upper:", s.str.upper().tolist())\nprint("title:", s.str.title().tolist())', details: 'Операции с символами (String methods).\n\n• Все строковые методы в pandas доступны ТОЛЬКО через префикс .str (называется accessor). s.lower() выкинет ошибку.\n• Все операции векторизованы на уровне C, применяются автоматически ко всем рядам колонки.\n• strip() — убирает пробелы (слева/справа), replace() — меняет текст.', link: PD + 'pandas.Series.str.lower.html' },
      { code: 'import pandas as pd\ns = pd.Series(["apple pie", "banana split", "cherry"])\nprint("contains:", s.str.contains("an").tolist())\nprint("startswith:", s.str.startswith("a").tolist())', details: 'Поиск подстрок и Регулярки.\n\n• s.str.contains("regex") — возвращает булеву маску. Идеально для фильтрации датасета: df[df["name"].str.contains("John")]\n• Если regex=True, строка внутри contains(...) воспринимается как Регулярное выражение (Regular Expression).', link: PD + 'pandas.Series.str.contains.html' },
      { code: 'import pandas as pd\ns = pd.Series(["a-b-c", "d-e", "f"])\nprint("split:", s.str.split("-").tolist())\nexpanded = s.str.split("-", expand=True)\nprint("expanded:\\n", expanded)', details: 'Разбиение (Split).\n\n• Базовый split() возвращает в каждой строке СПИСОК [list] из "осколков" строки.\n• С параметром expand=True происходит магия: списки разворачиваются каждый в ОТДЕЛЬНУЮ КОЛОНКУ внутри DataFrame. Часто применяется при разборе ФИО, логов или дат.', link: PD + 'pandas.Series.str.split.html' }
    ]) +
    sectionWithId('ref-pandas-reshape', 'Reshape: pivot, melt, stack', PD + 'pandas.pivot_table.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"A": ["foo", "foo", "bar"], "B": ["one", "two", "one"], "val": [1, 2, 3]})\npivot = pd.pivot_table(df, values="val", index="A", columns="B", aggfunc="sum", fill_value=0)\nprint(pivot)', details: 'Сводные таблицы (Pivot Tables).\n\n• Базовый Excel-инструмент для OLAP анализа, реализованный в Pandas.\n• index — какие колонки оставить на строках (ось Y).\n• columns — по значениям каких колонок развернуть столбцы (ось X).\n• aggfunc — метод расчета на перекрещении ("mean", "count", "sum").\n• fill_value — чем заполнить пустые ячейки (NaN), где нет пересечений (обычно нулем).', link: PD + 'pandas.pivot_table.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"name": ["A", "B"], "math": [90, 80], "eng": [85, 95]})\nmelted = pd.melt(df, id_vars=["name"], value_vars=["math", "eng"], var_name="subject", value_name="score")\nprint(melted)', details: 'Расплавление (Melt).\n\n• Прямая противоположность pivot_table! Переводит таблицу из "широкого" (Wide) формата (много колонок) в "длинный" (Long) формат (всего две колонки: признак-значение).\n• Необходима алгоритмики вроде seaborn.boxplot(data=df, x="variable", y="value"). Это "база" приведения форматов перед отправкой в модели, ожидающие 1D массивы (DeepSeek).', link: PD + 'pandas.melt.html' }
    ]) +
    sectionWithId('ref-pandas-apply', 'apply, map, transform, pipe', PD + 'pandas.DataFrame.apply.html', [
      { code: 'import pandas as pd\ndf = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})\nprint("apply по столбцам:\\n", df.apply(lambda col: col.max() - col.min()))\nprint("apply по строкам:\\n", df.apply(lambda row: row.sum(), axis=1))', details: 'Векторизованные функции через अप्लाई.\n\n• apply() — Медленная, но гибкая функция. Берет ЛЮБУЮ функцию/лябмду и прогоняет ее по массиву.\n• Невероятно помогает, когда невозможно использовать стандартный векторизованный код NumPy (например, сложные API звонки на каждую строчку).\n• axis=1 — применяется к каждой строке "вдоль". Для больших данных (n > 1m) рекомендуется pandarallel (многопоточный apply) или Dask.', link: PD + 'pandas.DataFrame.apply.html' },
      { code: 'import pandas as pd\ns = pd.Series([1, 2, 3])\nprint("map:\\n", s.map({1: "one", 2: "two", 3: "three"}).tolist())\nprint("map func:\\n", s.map(lambda x: x ** 2).tolist())', details: 'Map - Поэлементная обработка.\n\n• .map(dict) — мгновенно преобразует набор ключей (в Series) на их значения по словарю. Это супер-быстрый способ заменить "М", "Ж" на бинарные 1 и 0 (аналог Label encoding).\n• Очень быстрый lookup O(1) за счет хеширования под капотом (быстрее, чем apply).', link: PD + 'pandas.Series.map.html' },
      { code: 'import pandas as pd\ndf = pd.DataFrame({"a": [1, 2, 3]})\nresult = (df.pipe(lambda d: d * 2).pipe(lambda d: d + 10))\nprint(result)', details: 'Pipeline Pattern.\n\n• pipe(func) — Передает весь датафрейм (df) как первый аргумент в функцию.\n• Используется для формирования красивого конвейера предобработки (читаемого пайплайна). Избавляет от жуткой вложенности вида `func3(func2(func1(df)))`.', link: PD + 'pandas.DataFrame.pipe.html' }
    ]);
