    sectionWithId('ref-sklearn-linear', 'Линейные модели: Регрессия и ЛогРег', SK + 'sklearn.linear_model.LinearRegression.html', [
      { code: 'from sklearn.linear_model import LinearRegression\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprint("Weights:", model.coef_)\nprint("Bias:", model.intercept_)', details: 'Классическая линейная регрессия (МНК).\n\n• Самая базовая модель ($y = w_1x_1 + w_2x_2 + b$).\n• Обучается аналитически (Метод Наименьших Квадратов) без градиентного спуска (под капотом scipy.linalg.lstsq).\n• Не имеет гиперпараметров регуляризации.\n• Крайне чувствительна к коллинеарности признаков (когда x_1 и x_2 сильно коррелируют, веса w могут взорваться и стать огромными).', link: SK + 'sklearn.linear_model.LinearRegression.html' },
      { code: 'from sklearn.linear_model import Ridge, Lasso\n\nmodel_r = Ridge(alpha=1.0) # L2 регуляризация\nmodel_l = Lasso(alpha=0.1) # L1 регуляризация\nmodel_l.fit(X, y)\nprint("Lasso 0-weights:", sum(model_l.coef_ == 0))', details: 'Регуляризация (Ridge и Lasso).\n\n• Ridge (L2-штраф) — добавляет штраф $\\alpha \\sum w^2$. Уменьшает дисперсию модели (переобучение), заставляя веса быть близкими к нулю, но никогда не равными нулю. Лучший выбор по умолчанию!\n• Lasso (L1-штраф) — добавляет штраф $\\alpha \\sum |w|$. Выполняет АВТОМАТИЧЕСКИЙ ОТБОР ПРИЗНАКОВ: зануляет веса для неважных фичей.\n• ElasticNet — комбинация L1 и L2.', link: SK + 'sklearn.linear_model.Ridge.html' },
      { code: 'from sklearn.linear_model import LogisticRegression\n\nmodel = LogisticRegression(C=1.0, max_iter=1000)\nmodel.fit(X_train, y_train)\n# Предсказание классов (0 или 1)\npreds = model.predict(X_test)\n# Предсказание вероятностей\nprobs = model.predict_proba(X_test)', details: 'Логистическая регрессия (Классификация!).\n\n• Несмотря на название "Regression", это ЛИНЕЙНЫЙ КЛАССИФИКАТОР (выдает вероятности от 0 до 1 через сигмоиду).\n• C — обратная сила регуляризации. Меньше C -> сильнее штраф весов (сильнее борьба с переобучением).\n• predict_proba(X) возвращает вероятности (матрица [вероятность_0, вероятность_1]). Абсолютно необходима для ROC-AUC метрики.', link: SK + 'sklearn.linear_model.LogisticRegression.html' }
    ]) +
    sectionWithId('ref-sklearn-svm-tree-knn', 'SVM, Деревья, KNN', SK + 'sklearn.svm.SVC.html', [
      { code: 'from sklearn.svm import SVC\n\n# kernel="linear", "poly", "rbf", "sigmoid"\nmodel = SVC(kernel="rbf", C=1.0, gamma="scale")\nmodel.fit(X_train, y_train)\nprint("Support vectors:", len(model.support_))', details: 'Метод Опорных Векторов (Support Vector Machines).\n\n• Ищет гиперплоскость, которая максимально разделяет классы ("дорога"). Те точки, что лежат на границах дороги — это опорные векторы.\n• kernel="rbf" (ядровые трюки) — позволяет находить нелинейные кривые границы в многомерном пространстве.\n• ВНИМАНИЕ: Очень долго обучается на данных размера N > 100 000. ВНИМАНИЕ-2: Требует строгий StandardScaler() перед fit(), иначе сломается.', link: SK + 'sklearn.svm.SVC.html' },
      { code: 'from sklearn.tree import DecisionTreeClassifier, plot_tree\nimport matplotlib.pyplot as plt\n\nmodel = DecisionTreeClassifier(max_depth=3, min_samples_split=5)\nmodel.fit(X, y)\n# plot_tree(model, filled=True)\n# plt.show()', details: 'Дерево решений (Decision Trees).\n\n• Строит набор "IF-THEN" правил (делит пространство признаков прямоугольниками по Джини-критерию или Энтропии).\n• Главный враг дерева — чудовищное переобучение (overfitting). Дерево может выучить тренировочный датасет на 100% зазубрив каждую точку.\n• Лечение: max_depth (строго ограничить высоту), min_samples_split (мин. объектов в узле). Скейлинг признаков не нужен.', link: SK + 'sklearn.tree.DecisionTreeClassifier.html' },
      { code: 'from sklearn.neighbors import KNeighborsClassifier\n\nmodel = KNeighborsClassifier(n_neighbors=5, weights="distance")\nmodel.fit(X_train, y_train)\npreds = model.predict(X_test)', details: 'K-Ближайших соседей (KNN).\n\n• "Ленивое" обучение (model.fit() ничего не делает математически, просто сохраняет все данные в память дерева KD-Tree/Ball-Tree).\n• При вызове predict() ищет k=5 ближайших соседей по Эвклидовому расстоянию и забирает их мажоритарный класс.\n• Обязателен StandardScaler(). Очень медленный predict если датасет гигантский ($O(N \\log N)$). n_neighbors — главный параметр (слишком мал = переобучение, слишком велик = недообучение).', link: SK + 'sklearn.neighbors.KNeighborsClassifier.html' }
    ]) +
    sectionWithId('ref-sklearn-ensemble', 'Ансамбли: Лес, Градиентный бустинг', SK + 'sklearn.ensemble.RandomForestClassifier.html', [
      { code: 'from sklearn.ensemble import RandomForestClassifier\n\nmodel = RandomForestClassifier(n_estimators=100, max_depth=10, n_jobs=-1, random_state=42)\nmodel.fit(X_train, y_train)\n# Важность каждой фичи\nprint("Importance:", model.feature_importances_)', details: 'Случайный Лес (Random Forest).\n\n• Классика Kaggle. Бэггинг (Bagging) над сотней глубоких нерегуляризованных деревьев.\n• Каждое дерево учится независимо (n_jobs=-1 включает обучение на ВСЕХ ядрах процессора) на случайном сэмпле данных и признаков.\n• Удивительное свойство: Случайный лес практически НЕвозможно переобучить увеличением кол-ва деревьев (n_estimators). Просто растет время. Лучший инструмент "поставил и забыл".\n• Выдает feature_importances_ (на какие столбцы обращал больше внимания).', link: SK + 'sklearn.ensemble.RandomForestClassifier.html' },
      { code: 'from sklearn.ensemble import GradientBoostingClassifier\n\nmodel = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3)\nmodel.fit(X_train, y_train)\nprint("Score:", model.score(X_test, y_test))', details: 'Градиентный Бустинг (GBDT).\n\n• Последовательное ансамблирование. Каждое из 100 деревьев строится так, чтобы ИСПРАВИТЬ ОШИБКИ (антиградиент) предыдущего.\n• Строятся "пенечки" (очень мелкие деревья, max_depth=3-5).\n• Довольно медленный (не параллелится как лес). learning_rate — это влияние каждого нового дерева (чем меньше LR, тем больше нужно n_estimators).\n• Для серьезных задач лучше изучить аналоги: XGBoost, LightGBM, CatBoost.', link: SK + 'sklearn.ensemble.GradientBoostingClassifier.html' }
    ]);
